name: omega_flutter_lint
description: List of optimized and convenient rules used in Omega-R for streamlined development of Flutter projects
version: 3.0.0
repository: https://github.com/Omega-R/omega_flutter_lint
homepage: https://omega-r.com
environment:
  sdk: '>=2.19.0 <3.0.0'
